/* Free-plan friendly API client. Uses the Cloudflare Worker only. */
const CONFIG=Object.freeze({proxyBase:"/api",timezone:"Africa/Cairo",cacheTTL:{fixtures:1800000,live:180000,events:1800000,statistics:21600000,standings:86400000,leagues:604800000,teams:604800000,players:604800000},staleMaxAge:{fixtures:172800000,live:600000,events:86400000,statistics:21600000,standings:604800000,leagues:2592000000,teams:2592000000,players:2592000000}});
const memory=new Map(),inflight=new Map();
function keyFor(path,params={}){const q=new URLSearchParams();Object.keys(params).sort().forEach(k=>{const v=params[k];if(v!==undefined&&v!==null&&v!=="")q.set(k,String(v))});return `${path}?${q}`}
function read(key){try{const r=JSON.parse(localStorage.getItem(`kp:${key}`)||"null");return r?.data&&r.time?r:null}catch{return null}}
function save(key,data){const r={time:Date.now(),data};memory.set(key,r);try{localStorage.setItem(`kp:${key}`,JSON.stringify(r))}catch{}return data}
function stale(path,key){const r=memory.get(key)||read(key);if(!r)return null;const max=CONFIG.staleMaxAge[path]??86400000;if(Date.now()-r.time<=max){memory.set(key,r);return r.data}return null}
async function fetchJSON(url){const res=await fetch(url,{headers:{Accept:"application/json"},cache:"no-store"});let body=null;try{body=await res.json()}catch{}if(res.ok&&!body?.error)return body;const e=new Error(body?.error||`HTTP ${res.status}`);e.status=res.status;e.apiErrors=body?.errors;throw e}
async function request(path,params={},options={}){const clean={...params,timezone:params.timezone??CONFIG.timezone};const key=keyFor(path,clean),ttl=options.ttl??30000,force=options.force===true,now=Date.now();const m=memory.get(key);if(!force&&m&&now-m.time<ttl)return m.data;const l=read(key);if(!force&&l){memory.set(key,l);if(now-l.time<ttl)return l.data}if(inflight.has(key))return inflight.get(key);const p=(async()=>{const q=new URLSearchParams();Object.entries(clean).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=="")q.set(k,v)});try{return save(key,await fetchJSON(`${CONFIG.proxyBase}/${path}?${q}`))}catch(e){const old=stale(path,key);if(old){console.warn("Kora Plus: using cached data",path);return old}throw e}})();inflight.set(key,p);try{return await p}finally{inflight.delete(key)}}
export const api={getFixtures:(p={},o={})=>request("fixtures",p,{ttl:CONFIG.cacheTTL.fixtures,...o}),getLiveMatches:(p={},o={})=>request("fixtures",{live:"all",...p},{ttl:CONFIG.cacheTTL.live,...o}),getMatchDetails:(fixture,o={})=>request("fixtures",{id:fixture},{ttl:CONFIG.cacheTTL.fixtures,...o}),getMatchEvents:(fixture,o={})=>request("fixtures/events",{fixture},{ttl:CONFIG.cacheTTL.events,...o}),getLineups:(fixture,o={})=>request("fixtures/lineups",{fixture},{ttl:CONFIG.cacheTTL.events,...o}),getMatchStatistics:(fixture,o={})=>request("fixtures/statistics",{fixture},{ttl:CONFIG.cacheTTL.statistics,...o}),getStandings:(league,season,o={})=>request("standings",{league,season},{ttl:CONFIG.cacheTTL.standings,...o}),getLeagues:(p={},o={})=>request("leagues",p,{ttl:CONFIG.cacheTTL.leagues,...o}),getTeams:(p={},o={})=>request("teams",p,{ttl:CONFIG.cacheTTL.teams,...o}),getPlayers:(p={},o={})=>request("players",p,{ttl:CONFIG.cacheTTL.players,...o}),getHeadToHead:(h2h,o={})=>request("fixtures/headtohead",{h2h},{ttl:CONFIG.cacheTTL.events,...o})};
export {CONFIG};
